---
title: "workout01-cassandra-tang"
output: github_document
---

#GSW Team Shots Report

##Introduction
This report examines and visualizes the shooting patterns of the starting lineup of the Golden State Warriors from the 2016-2017 season. By examining the data from their 2016-2017 season, we can pick out trends in attempted and made shots and make suggestions where to focus on training and in shooting in a game. \n
\n

##Motivation and Background
Stephen Curry is an outrageous 3-point shooter. He and Kevin Durant are the major play-makers. Klay Thompson is a major facilitator of plays and catch-and-shoot. Andre Iguodala and Draymond Green are two excellent defenders. Together, the five of them make up a Dream Team of a starting line-up and have propelled the Golden State Warriors to fame and success. Why are they successful, in terms of observable points? Where are there strengths, their weaknesses, and do these correspond well with their current positions? We should hope so, otherwise someone isn't doing their job. So let's check the coach's work, shall we?
\n
\n

##Data
Of 1250 shots, Curry has made 584. Of 915 shots, Durant has made 495. Of 578 shots, Green has made 245. Of 371 shots, Iguodala has made 192. Of 1220 shots, Thompson has made 575.
```{r, include = TRUE, echo = FALSE}
setwd("~/Desktop/Stats 133/statsgit/workout01/code")
library(dplyr)
library(ggplot2)

data <- read.csv("../data/shots-data.csv", stringsAsFactors = FALSE)

table_header <- list(c("Stephen Curry", "Kevin Durant", "Draymond Green", "Andre Iguodala", "Klay Thompson"),c("Name", "Total Shots", "Shots Made", "Percent Made"))

name <- c("Stephen Curry", "Kevin Durant", "Draymond Green", "Andre Iguodala", "Klay Thompson")

total <- c(nrow(filter(data, data$name == "Stephen Curry")), nrow(filter(data, data$name == "Kevin Durant")), nrow(filter(data, data$name == "Draymond Green")), nrow(filter(data, data$name == "Andre Iguodala")), nrow(filter(data, data$name == "Klay Thompson")))

total2 <- c(nrow(filter(data, data$name == "Stephen Curry" & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Kevin Durant" & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Draymond Green" & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Andre Iguodala" & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Klay Thompson" & shot_type == "2PT Field Goal")))

total3 <- c(nrow(filter(data, data$name == "Stephen Curry" & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Kevin Durant" & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Draymond Green" & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Andre Iguodala" & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Klay Thompson" & shot_type == "3PT Field Goal")))

made <- c(nrow(filter(data, data$name == "Stephen Curry" & data$shot_made_flag == 'shot_yes')), nrow(filter(data, data$name == "Kevin Durant" & data$shot_made_flag == 'shot_yes')), nrow(filter(data, data$name == "Draymond Green" & data$shot_made_flag == 'shot_yes')), nrow(filter(data, data$name == "Andre Iguodala" & data$shot_made_flag == 'shot_yes')), nrow(filter(data, data$name == "Klay Thompson" & data$shot_made_flag == 'shot_yes')))

made2 <- c(nrow(filter(data, data$name == "Stephen Curry" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Kevin Durant" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Draymond Green" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Andre Iguodala" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Klay Thompson" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")))

made3 <- c(nrow(filter(data, data$name == "Stephen Curry" & data$shot_made_flag == 'shot_yes' & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Kevin Durant" & data$shot_made_flag == 'shot_yes' & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Draymond Green" & data$shot_made_flag == 'shot_yes' & shot_type == "3PT Field Goal")), nrow(filter(data, data$name == "Andre Iguodala" & data$shot_made_flag == 'shot_yes' & shot_type == "2PT Field Goal")), nrow(filter(data, data$name == "Klay Thompson" & data$shot_made_flag == 'shot_yes' & shot_type == "3PT Field Goal")))

perc_made <- c(nrow(filter(data, data$name == "Stephen Curry" & data$shot_made_flag == 'shot_yes'))/nrow(filter(data, data$name == "Stephen Curry")) * 100, nrow(filter(data, data$name == "Kevin Durant" & data$shot_made_flag == 'shot_yes'))/nrow(filter(data, data$name == "Kevin Durant")) * 100, nrow(filter(data, data$name == "Draymond Green" & data$shot_made_flag == 'shot_yes'))/nrow(filter(data, data$name == "Draymond Green")) * 100, nrow(filter(data, data$name == "Andre Iguodala" & data$shot_made_flag == 'shot_yes'))/nrow(filter(data, data$name == "Andre Iguodala")) * 100, nrow(filter(data, data$name == "Klay Thompson" & data$shot_made_flag == 'shot_yes'))/nrow(filter(data, data$name == "Klay Thompson")) * 100)

perc_made2 <- made2/total2 * 100

perc_made3 <- made3/total3 * 100

table_data <- matrix(c(name, total, made, perc_made), nrow = 5, ncol = 4, dimnames = table_header)

table_data2 <- matrix(c(name, total2, made2, perc_made2), nrow = 5, ncol = 4, dimnames = table_header)

table_data3 <- matrix(c(name, total3, made3, perc_made3), nrow = 5, ncol = 4, dimnames = table_header)

table_data <- as.data.frame(table_data)
table_data <- arrange(table_data, desc(perc_made))

table_data2 <- as.data.frame(table_data2)
table_data2 <- arrange(table_data2, desc(perc_made2))

table_data3 <- as.data.frame(table_data3)
table_data3 <- arrange(table_data3, desc(perc_made3))

knitr::kable(table_data, caption = "Overall Shooting Accuracy per Player")
knitr::kable(table_data2, caption = "2-Point Field Goal Shooting Accuracy per Player")
knitr::kable(table_data3, caption = "3-Point Field Goal Shooting Accuracy per Player")
```

\n
\n

##Analysis
It is plain to see that Andre Iguodala makes significantly fewer shots than the rest of the fantastic five. However, Iguodala has the second highest overall accuracy of the five of them, surpassed only by Kevin Durant. Although we do not have the defensive statistics on the players, we can infer who is primarily defensive and who is primarily offensive. Curry has the most dispersion of shots, as visible in the 
\n
\n

##Discussion

\n
\n

##Conclusion

\n
\n

##References

